Update build_all.yml

diff --git a/.github/workflows/build_all.yml b/.github/workflows/build_all.yml
--- a/.github/workflows/build_all.yml
+++ b/.github/workflows/build_all.yml
@@ -73,24 +73,27 @@ jobs:
           RUN ln -sf /usr/bin/python3.8 /usr/bin/python3 && \
               ln -sf /usr/bin/python3 /usr/bin/python
 
-          # Install pip for all Python versions
-          # RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.8 && \
-          #     curl -sS https://bootstrap.pypa.io/get-pip.py | python3.9 && \
-          #     curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 && \
-          #     curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
-          #     curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12
-          RUN python3.8 -m ensurepip --upgrade && \
-              python3.9 -m ensurepip --upgrade && \
-              python3.10 -m ensurepip --upgrade && \
-              python3.11 -m ensurepip --upgrade && \
-              python3.12 -m ensurepip --upgrade
-
+          # Create a script to reliably install pip for all Python versions
+          RUN echo '#!/bin/bash \n\
+              for version in 3.8 3.9 3.10 3.11 3.12; do \n\
+                echo "Installing pip for Python $version" \n\
+                # Try using ensurepip first \n\
+                python$version -m ensurepip --upgrade || true \n\
+                # If that fails, download get-pip.py \n\
+                if ! command -v python$version -m pip &>/dev/null; then \n\
+                  curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py \n\
+                  python$version /tmp/get-pip.py \n\
+                fi \n\
+                # Verify pip is installed \n\
+                python$version -m pip --version \n\
+              done' > /tmp/install_pip.sh && chmod +x /tmp/install_pip.sh && /tmp/install_pip.sh
+          
           # Install dependencies for PyTorch for all Python versions
-          RUN python3.8 -m pip install wheel setuptools numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions && \
-              python3.9 -m pip install wheel setuptools numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions && \
-              python3.10 -m pip install wheel setuptools numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions && \
-              python3.11 -m pip install wheel setuptools numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions && \
-              python3.12 -m pip install wheel setuptools numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions
+          RUN for version in 3.8 3.9 3.10 3.11 3.12; do \
+              python$version -m pip install --no-cache-dir wheel setuptools && \
+              python$version -m pip install --no-cache-dir numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions; \
+              done
+
 
           # Set environment variables for build
           ENV USE_CUDA=1 \
